import { Box, Container, Flex } from '@chakra-ui/react';
import ApplicationProviders from '@providers/Providers';
import { fonts } from '@styles/fonts';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Puzzle Ecommerce',
  description: 'Generated by PuzzleFasillari Team',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" data-theme="light" className={fonts.inter.className}>
      <body>
        <ApplicationProviders>
          <Container maxW="container.lg" minHeight="100vh">
            <Flex justify="center" align="center" minHeight={'100vh'}>
              <Box w="xl" boxShadow="2xl" px="10" py={10} rounded="md">
                {children}
              </Box>
            </Flex>
          </Container>
        </ApplicationProviders>
      </body>
    </html>
  );
}
