import Navbar from '@components/Navbar/Navbar';
import ApplicationProviders from '@providers/Providers';
import '@styles/global.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Puzzle Ecommerce',
  description: 'Generated by PuzzleFasillari Team',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="light">
      <body>
        <ApplicationProviders>
          <Navbar />
          {children}
          {/* <Footer /> */}
        </ApplicationProviders>
      </body>
    </html>
  );
}
