import type { Metadata } from 'next';
import ApplicationProviders from '@/providers/Providers';
import { RootContainer } from '@/styles/pages/home';
import Navbar from '@/components/Navbar/Navbar';

export const metadata: Metadata = {
  title: 'Puzzle Ecommerce',
  description: 'Generated by PuzzleFasillari Team',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ApplicationProviders>
          <RootContainer>
            <Navbar />
            {children}
            {/* <Footer /> */}
          </RootContainer>
        </ApplicationProviders>
      </body>
    </html>
  );
}
