import { Container } from '@chakra-ui/react';
import Navbar from '@components/Navbar/Navbar';
import ApplicationProviders from '@providers/Providers';
import { fonts } from '@styles/fonts';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Puzzle Ecommerce',
  description: 'Generated by PuzzleFasillari Team',
};
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" data-theme="light" className={fonts.inter.className}>
      <body>
        <ApplicationProviders>
          <Navbar />
          <Container minHeight="100vh" maxW="container.xl">
            {children}
          </Container>
        </ApplicationProviders>
      </body>
    </html>
  );
}
